### ISSUE TITLE
Could not submit job under CEPCSW enviroment

### ISSUE THREAD

**Issue by ihepzhangyao** [cepc/CEPCSW#139]
Could not submit job under CEPCSW enviroment. The error `ImportError: No module named site` raised.

**Comment by mirguest** [comment]
Please consider to use a "clean" environment. 
Tao

**Comment by ihepzhangyao** [comment]
If it is caused by conflic of python or other library version between CEPCSW and condor job script. Could we ask for a compatible script?

**Comment by mirguest** [comment]
Hi @ihepzhangyao,
Yes, we can consider about such wrapper.

I have a quick test using `env` to start a clean environment:
```bash
$ env -i SHELL=/bin/bash /cvmfs/common.ihep.ac.cn/cc/sysgroup/hep_job/bin/hep_q
```

**Comment by ihepzhangyao** [comment]
That works. Thanks!
