### ISSUE TITLE
CMake issue: HepMC not found

### ISSUE THREAD

**Issue by vvolkl** [cepc/CEPCSW#146]
I just checked the spack build of cepcsw v0.2.0 and see the following warning in the build log (/cvmfs/sw.hsf.org/spackages/linux-centos7-broadwell/gcc-8.3.0/cepcsw-0.2.0-qnxsfg3cdx6riyzkgzjxrcrp7uggnl3q/.spack/spack-build-out.txt):

```
CMake Warning at cmake/CEPCSWDependencies.cmake:27 (find_package):
  By not providing "FindHepMC.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "HepMC", but
  CMake did not find one.

  Could not find a package configuration file provided by "HepMC" with any of
  the following names:

    HepMCConfig.cmake
    hepmc-config.cmake

  Add the installation prefix of "HepMC" to CMAKE_PREFIX_PATH or set
  "HepMC_DIR" to a directory containing one of the above files.  If "HepMC"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:31 (include)
```
Indeed CEPCSW does not provide a `FindHepMC.cmake`. This is necessary for HepMC2 (HepMC3 already provides its CMake configuration and targets). I'd recommend using https://github.com/HSF/cmaketools, which includes a `FindHepMC.cmake`. Alternatively, you could also copy it to the cmake folder. Maybe this is not an issue when using the lcg releases, as they already set up the cmaketools package.

**Comment by mirguest** [comment]
Thanks @vvolkl , I will copy the `FindHepMC.cmake` from cmaketools.
Tao
