### ISSUE TITLE
2GB additional memeory usage when use the geometry of ECAL in CRD

### ISSUE THREAD

**Issue by mirguest** [cepc/CEPCSW#156]
Hi @fucd , please coordinate with Fangyi. Thanks!
Tao

**Comment by qwert2333** [comment]
Hi @mirguest @fucd I tried to fix this issue and submitted a merge request: https://github.com/cepc/CEPCSW/pull/161
In my local test the memory is much smaller than before, please have a check, thanks!
Fangyi

**Comment by mirguest** [comment]
As @qwert2333 optimize the geometry, the memory problem should be fixed now.
