### ISSUE TITLE
Examples of CEPCSW can't get MC information of  final-state particals

### ISSUE THREAD

**Issue by zyzhao0** [cepc/CEPCSW#158]
When I run the example of  _CEPCSW/Examples/options/detsim_Pan_ana.root_ in CEPCSW, I set the gun. Particles as "pi0". I can't get the MC information of 2 gammas in final state. The _N_mc_ , number of MC particals, is always 1. The only MC information I can get are pi0's . Can I get the information of MC gammas?

```
======> EVENT:4
 N_mc            = 1
 N_rec           = 2
 m_pReco_PID     = 22,
                  22
 m_pReco_mass    = 0,
                  0
 m_pReco_energy  = 7.50405,
                  2.05038
 m_pReco_px      = 7.39686,
                  2.01176
 m_pReco_py      = -0.044182,
                  0.0341337
 m_pReco_pz      = 1.26302,
                  0.394613
 m_pReco_charge  = 0,
                  0
 m_mc_p_size     = 0
 m_mc_pid        = 111
 m_mc_mass       = 0.134977
 m_mc_px         = 9.84808
 m_mc_py         = 0
 m_mc_pz         = 1.73648
 m_mc_charge     = 0
 m_hasConversion = 0
 m_marlinTrack   = 0

```

**Comment by mirguest** [comment]
Hi @wenxingfang ,
Could you have a look at this problem? Thanks.
Tao

**Comment by wenxingfang** [comment]
Hi @zyzhao0 and @mirguest 

I think it is because the decay of pi0 is simulated by Geant4, and the two gammas in Geant4 are not saved in MCParticle collection. Therefore, you will only get one pi0 but not two gammas.
@mirguest  do you think it is possible to save the two gammas in simulation ?

Best,
Wenxing

**Comment by mirguest** [comment]
Hi @wenxingfang ,
I have just checked the simulation, the decayed secondary particles should be stored into MC particle collection.
Could you have a check?
Tao

**Comment by wenxingfang** [comment]
Hi @mirguest 

Ok, I will have a check.

Best,
Wenxing

**Comment by wenxingfang** [comment]
Hi @zyzhao0 

Could you try to comment this line (https://github.com/cepc/CEPCSW/blob/master/Reconstruction/PFA/Pandora/GaudiPandora/src/PandoraPFAlg.cpp#L617)  and see if you can get pi0 now?

Best,
Wenxing

**Comment by zyzhao0** [comment]
Hi @wenxingfang 

I have commented that line, but it doesn't work.  There is still no MC information of gammas.

```
======> EVENT:1
 N_mc            = 1
 N_rec           = 2
 m_pReco_PID     = 22,
                  22
 m_pReco_mass    = 0,
                  0
 m_pReco_energy  = 6.35047,
                  2.77321
 m_pReco_px      = 6.25199,
                  2.73157
 m_pReco_py      = -0.0603998,
                  0.0548139
 m_pReco_pz      = 1.1124,
                  0.475576
 m_pReco_charge  = 0,
                  0
 m_mc_p_size     = 0
 m_mc_pid        = 111
 m_mc_mass       = 0.134977
 m_mc_px         = 9.84808
 m_mc_py         = 0
 m_mc_pz         = 1.73648
 m_mc_charge     = 0
 m_hasConversion = 0
 m_marlinTrack   = 0
```


best, 
Zhiyu Zhao

**Comment by wenxingfang** [comment]
Hi @zyzhao0 ,

Do you use latest version of CEPCSW ? Could you try with latest version? By the way, do you recompile the CEPCSW after this change?

Best,
Wenxing

**Comment by zyzhao0** [comment]
Hi @wenxingfang ,

     I think my version is the lastest one. But I didn't recompile CEPCSW. I will try to recompile it and update to the lastest version.

Best,
Zhiyu Zhao

**Comment by zyzhao0** [comment]
Hi @wenxingfang and @mirguest ,
      Thank you very much! I could get MC gammas. 
      I have commented that line(https://github.com/cepc/CEPCSW/blob/master/Reconstruction/PFA/Pandora/GaudiPandora/src/PandoraPFAlg.cpp#L617) with a wrong symbol "#".  After using "//" to comment it and rebuild the CEPCSW by using "./build.sh" command, it works!
```
======> EVENT:0
 N_mc            = 3
 N_rec           = 2
 m_pReco_PID     = 22,
                  22
 m_pReco_mass    = 0,
                  0
 m_pReco_energy  = 6.20517,
                  2.60328
 m_pReco_px      = 6.10213,
                  2.57125
 m_pReco_py      = 0.0228788,
                  -0.0225887
 m_pReco_pz      = 1.12588,
                  0.406465
 m_pReco_charge  = 0,
                  0
 m_mc_p_size     = 0,
                  1, 1
 m_mc_pid        = 111,
                  22, 22
 m_mc_mass       = 0.134977,
                  0, 0
 m_mc_px         = 9.84808,
                  7.18984, 2.65824
 m_mc_py         = 0,
                  0.0251839, -0.0251839
 m_mc_pz         = 1.73648,
                  1.3229, 0.413585
 m_mc_charge     = 0,
                  0, 0
 m_hasConversion = 0
 m_marlinTrack   = 0
```

Best,
Zhiyu Zhao
