### ISSUE TITLE
CEPCSW build failure in Key4hep Nightlies

### ISSUE THREAD

**Issue by vvolkl** [cepc/CEPCSW#159]
https://gitlab.cern.ch/key4hep/k4-deploy/-/jobs/13243984

probably was introduced yesterday.

**Comment by mirguest** [comment]
Hi @vvolkl, 
Thanks for letting us know. 
It looks like that DD4hep had removed the DDG4 legacy, which is still used in the current CEPCSW. I will update it soon. 

Tao

**Comment by mirguest** [comment]
Hi @vvolkl ,
Could you rebuild the Key4hep with the latest CEPCSW? Thank you!
Tao

**Comment by vvolkl** [comment]
Thanks @mirguest, yes, I believe it was the legacy sensitive detectors that were being removed in dd4hep, the most recent build worked again.
