### ISSUE TITLE
Use edm4hep::Const* types for compatibility with newer podio

### ISSUE THREAD

**Issue by vvolkl** [cepc/CEPCSW#184]
Currently, cepcsw cannot be built in the nightlies because https://github.com/AIDASoft/podio/pull/193 means that edm4hep interfaces now should use the Const* types.

Unfortunately, the typenames will change again soon (https://github.com/AIDASoft/podio/pull/205), so maybe you prefer to wait until after that one is merged with fixing this issue, but it will be necessary in order to make a new release of the full key4hep software.

The current nightly builds don't include cepcsw until this issue is fixed, but should have all the dependencies and can be used for testing:

```
source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
```

**Comment by mirguest** [comment]
Hi @vvolkl ,
Thank you for letting us know about the changes. We would prefer to wait a bit.
Tao

**Comment by mirguest** [comment]
Hi @vvolkl ,
I update the edm4hep interfaces in CEPCSW in #185 . The "auto" is used to avoid the explict typename. 
Could you build CEPCSW with the nightlies again? Is that possible to enable the Garfield++ in the nightlies? 
Thank you again. 
Tao

**Comment by vvolkl** [comment]
Hi Tao Lin, ok! we're still debugging a test failure with the wrapper, I'll let you know when I have added Garfield.

**Comment by mirguest** [comment]
> Hi Tao Lin, ok! we're still debugging a test failure with the wrapper, I'll let you know when I have added Garfield.

Thanks Valentin.

**Comment by mirguest** [comment]
@vvolkl Thanks again. I know the reason. Because Genfit is not built in the nightlies version, so the cmake skip this module. That's why I don't find the problem.
Tao
