### ISSUE TITLE
WIP: Unify the MarlinUtil in CEPCSW

### ISSUE THREAD

**Issue by mirguest** [cepc/CEPCSW#19]
Hi @fucd and @wenxingfang,

I found both of you have contributed the classes such as `HelixClass` and `LineClass`, 
* https://github.com/cepc/CEPCSW/tree/master/Utilities/DataHelper
* https://github.com/cepc/CEPCSW/tree/master/Reconstruction/PFA/Pandora/MarlinUtil/01-08/source

To avoid duplication, please consider to put all the same classes together.

Tao

**Comment by wenxingfang** [comment]
Hi @mirguest and @fucd 
There is one difference about HelixClass.cc between mine and @fucd  which is #include "ced_cli.h", can I ask why you commented the #include "ced_cli.h" ?

**Comment by fucd** [comment]
Hi @wenxingfang,

CED is a draw tool, removed in my tracking algrithom, if you hope continue to use CED, it can be modified to include it.

Chengdong

**Comment by fucd** [comment]
Hi @wenxingfang and @mirguest,

In addition, HelixClass does not use any component of ced_cli.h in fact, the include seems not needed.

Chengdong

**Comment by wenxingfang** [comment]
Hi @fucd 
Thanks for the explanation! I can remove the HelixClass and LineClass in my MarlinUtil/01-08/source. For the ClusterShapes class it need old version GSL/1.14，e.g. https://github.com/cepc/CEPCSW/blob/master/Reconstruction/PFA/Pandora/GaudiPandora/CMakeLists.txt#L6
Do you want to add ClusterShapes in your DataHelper? Otherwise, I will keep it in MarlinUtil/01-08/source

Wenxing

**Comment by mirguest** [comment]
> Hi @fucd
> Thanks for the explanation! I can remove the HelixClass and LineClass in my MarlinUtil/01-08/source. For the ClusterShapes class it need old version GSL/1.14，e.g. https://github.com/cepc/CEPCSW/blob/master/Reconstruction/PFA/Pandora/GaudiPandora/CMakeLists.txt#L6
> Do you want to add ClusterShapes in your DataHelper? Otherwise, I will keep it in MarlinUtil/01-08/source
> 
> Wenxing

Hi Wenxing, I think you can put all the files from MarlinUtil into DataHelper. Just remove the `MarlinUtil/01-08/source` to keep the structure look well.

Tao

**Comment by wenxingfang** [comment]
Hi @mirguest 
Ok, I will try to do it.

Wenxing

**Comment by mirguest** [comment]
Hi @wenxingfang ,
Another issue is the link to GSL 1.14 in https://github.com/cepc/CEPCSW/blob/master/Utilities/DataHelper/CMakeLists.txt

Please resolve such issue.

Tao

**Comment by mirguest** [comment]
Hi @fucd , you have a hard coded path in our code:
* https://github.com/cepc/CEPCSW/blob/master/Utilities/KalDet/CMakeLists.txt#L34

Please fixed this issue.

Tao

**Comment by mirguest** [comment]
Hi @fucd , I have a quick fix on this issue, please have a look at PR #23 and test it. 
Thank you.

Tao
