### ISSUE TITLE
Bugs in CEPCSW/Utilities/DataHelper/src/Navigation.cpp

### ISSUE THREAD

**Issue by qwert2333** [cepc/CEPCSW#202]
Dear developers, 
  Hello, I checked out the latest CEPCSW version, and found there is an error when compiling: 

cefs/higgs/guofy/CEPCSW/Utilities/DataHelper/src/Navigation.cpp:77:61: error: no matching function for call to ‘std::vector<edm4hep::SimTrackerHit>::push_back(const edm4hep::ConstSimTrackerHit)’
       else if(ass.getRec()==hit) hits.push_back(ass.getSim());

Could you please have a look?

**Comment by mirguest** [comment]
Dear Fangyi, 
The EDM4hep is changed a bit, which cause the interface change. I will release a new version with the new EDM4hep when EDM4hep is released. 
Tao
