### ISSUE TITLE
Update of edm4hep track covariance matrix dimensions

### ISSUE THREAD

**Issue by vvolkl** [cepc/CEPCSW#217]
In https://github.com/key4hep/EDM4hep/pull/138, we added time information to the track state, and enlarged the track covariance matrix with the new time information.
The indices for the existing entries of the covariance matrix should stay the same, but the type `std::array<float, 15>` of the matrix must be changed to `std::array<float, 21>` in several places in cepcsw (or deducted from `edm4hep::TrackState` where possible) .

**Comment by mirguest** [comment]
Hi @vvolkl ,
Thank you for letting us know. I will update the related code in CEPCSW. 
Tao
