### ISSUE TITLE
WIP: MC truth

### ISSUE THREAD

**Issue by fucd** [cepc/CEPCSW#234]
* MCParticleG4 is unknown for most of people
* SimTrackerHit and SimCalorimeterHit sometimes has wrong MCParticle object, because TrackID in Geant4 tracking is not always equal to the id of MCParticle in the collection
* Requirement: backscattering particles are also needed to save into MCParticle collection, since it is helpful to analysis the performance of tracking.

**Comment by mirguest** [comment]
@fucd could you provide an example so I could debug with the second issue? For the backscattering particles, could you provide the definition? Thanks.

**Comment by mirguest** [comment]
From Chengdong:
> 2. Example: 1st event in /cefs/data/stdhep/CEPC250/higgs/E250.Pbbh.whizard195/E250.Pbbh_X.e0.p0.whizard195/Pbbh_X.e0.p0.00001.stdhep
has hits:
HitID     G4TrackID         linked MCParticleID
0           97                     96
but in fact MCParticle(id=96) is a GeneratorStatus=2 particle
> 
> 3. Backscattering is defined as which move from out of tracker to tracker, like in UserSteppingAction of Mokka:
> 
> G4ThreeVector pre = aStep->GetPreStepPoint()->GetPosition();
G4bool PrePointInsideTrackerRegion = theCGAGeometryManager->GetTrackerRegionRmax() > pre.perp() && theCGAGeometryManager->GetTrackerRegionZmax() > std::fabs(pre.z());
G4ThreeVector post = aStep->GetPostStepPoint()->GetPosition();
G4bool PostPointInsideTrackerRegion = theCGAGeometryManager->GetTrackerRegionRmax() > post.perp() && theCGAGeometryManager->GetTrackerRegionZmax() > std::fabs(post.z());
G4bool isBackscattering = !(PrePointInsideTrackerRegion) && PostPointInsideTrackerRegion;
> 
> where theCGAGeometryManager->GetTrackerRegionRmax() and theCGAGeometryManager->GetTrackerRegionZmax() define the range of tracker region.
Now in CEPCSW, DD4hep constants have defined "tracker_region_zmax" and "tracker_region_rmax", but I am not sure whether can read DD4hep constants in our simulation interface.
Or another way, we can define Region like "DriftChamberRegion" for DC. How about them?

**Comment by mirguest** [comment]
Hi @fucd ,

For the second issue, could you try my latest PR: https://github.com/cepc/CEPCSW/pull/239

Thank you.

Tao

**Comment by mirguest** [comment]
Hi @fucd ,

For the third issue, could you try PR #240 ?

I use DD4hep to access the constants from the XML files. 

Tao

**Comment by fucd** [comment]
Hi @mirguest ,

Yes, they are what I want. Thank you very much!
Just a remind, GenPrinter and CommonUserEventInfo give many print out now.

Best,
Chengdong

**Comment by mirguest** [comment]
Hi @fucd ,

Thank you for the testing. I will create another PR to mute them. 

Tao

**Comment by fucd** [comment]
@mirguest Prefect! I will close this issue in earlier.
