### ISSUE TITLE
Memory leakage in reading and processing Podio

### ISSUE THREAD

**Issue by qwert2333** [cepc/CEPCSW#244]
Hi, 
  When processing the events in CEPCSW, I find there might be some memory leakage problem. I switched off all my own processes and read the Podio file with PodioInput, and monitor the memory with 'top'. 
  My script 'readDigi.py' is attached here: 
[readDigi.txt](https://github.com/cepc/CEPCSW/files/11229412/readDigi.txt)
The readin file '/scratchfs/atlas/guofy/CEPCSW/run/SimSample/E240_nnHgg/E240_nnHgg_22.root' contains 400 ee->ZH->nunugg events.  

  The script to monitor the memory is:

`#!/bin/bash

while true; do
    pid=$(pgrep -u guofy python)
    if [ -z "$pid" ]; then
        echo "No gaudirun process found."
    else
        mem=$(top -b -n1 -p $pid | awk 'NR>7 { sum += $6 } END { print sum }')
        echo "Process (PID $pid) memory usage: $mem "
    fi
    sleep 1
done`

And the result is (auto unit in 'top', so max to 8g at the end ): 

> Process (PID 32743) memory usage: 9336
> Process (PID 32743) memory usage: 71280
> Process (PID 32743) memory usage: 109716
> Process (PID 32743) memory usage: 211456
> Process (PID 32743) memory usage: 230688
> Process (PID 32743) memory usage: 247340
> Process (PID 32743) memory usage: 287788
> Process (PID 32743) memory usage: 316424
> Process (PID 32743) memory usage: 339716
> Process (PID 32743) memory usage: 397004
> Process (PID 32743) memory usage: 460620
> Process (PID 32743) memory usage: 643872
> Process (PID 32743) memory usage: 807452
> Process (PID 32743) memory usage: 990.3
> Process (PID 32743) memory usage: 1.1
> Process (PID 32743) memory usage: 1.3
> Process (PID 32743) memory usage: 1.5
> Process (PID 32743) memory usage: 1.7
> Process (PID 32743) memory usage: 1.8
> Process (PID 32743) memory usage: 2
> Process (PID 32743) memory usage: 2.2
> Process (PID 32743) memory usage: 2.3
> Process (PID 32743) memory usage: 2.5
> Process (PID 32743) memory usage: 2.7
> Process (PID 32743) memory usage: 2.9
> Process (PID 32743) memory usage: 3.2
> Process (PID 32743) memory usage: 3.4
> Process (PID 32743) memory usage: 3.7
> Process (PID 32743) memory usage: 3.9
> Process (PID 32743) memory usage: 4.1
> Process (PID 32743) memory usage: 4.3
> Process (PID 32743) memory usage: 4.5
> Process (PID 32743) memory usage: 4.8
> Process (PID 32743) memory usage: 5
> Process (PID 32743) memory usage: 5.2
> Process (PID 32743) memory usage: 5.3
> Process (PID 32743) memory usage: 5.6
> Process (PID 32743) memory usage: 5.8
> Process (PID 32743) memory usage: 6
> Process (PID 32743) memory usage: 6.1
> Process (PID 32743) memory usage: 6.4
> Process (PID 32743) memory usage: 6.5
> Process (PID 32743) memory usage: 6.7
> Process (PID 32743) memory usage: 6.9
> Process (PID 32743) memory usage: 7.1
> Process (PID 32743) memory usage: 7.2
> Process (PID 32743) memory usage: 7.5
> Process (PID 32743) memory usage: 7.7
> Process (PID 32743) memory usage: 7.9
> Process (PID 32743) memory usage: 8.2
> Process (PID 32743) memory usage: 0

  Could you please have a check? This is really important to the large statistics performance analysis in CEPCSW. 
  Thank you!

Best,
Fangyi

**Comment by mirguest** [comment]
# Summary

| Max Memory (KB)  | read only | read + write |
| -|------|--------|
| MCParticle | 626256 | 634496 |
| MCParticle + EcalBarrelCollectionMerged | 5296160 | 5441688 |
| EcalBarrelCollectionMerged  | 5320304 | 5424008 |

# Podio reader only
## load MCParticle
```bash
$ /usr/bin/time -v gaudirun.py readDigi.py
        Maximum resident set size (kbytes): 626256
```

## load MCParticle + EcalBarrelCollectionMerged
```
        Maximum resident set size (kbytes): 5296160
```


# Podio reader + writer
## load + write MCParticle 
```
        Maximum resident set size (kbytes): 634496
```

## load + write MCParticle + EcalBarrelCollectionMerged
```
        Maximum resident set size (kbytes): 5441688
```

**Comment by mirguest** [comment]
Use valgrind massif to check the memory usage. Run gaudirun.py with the profiler name:
```
$ /usr/bin/time -v gaudirun.py --profilerName valgrindmassif readDigi.py
# setting LC_ALL to "C"
# ------ Profiling options are on ------
#  o Profiler: valgrind
#  o Options: '--tool=massif --massif-out-file=valgrindmassif.output.log'.
#  o Output: valgrindmassif.output.log
==19843== Massif, a heap profiler
==19843== Copyright (C) 2003-2017, and GNU GPL'd, by Nicholas Nethercote
==19843== Using Valgrind-3.20.0 and LibVEX; rerun with -h for copyright info
==19843== Command: python /cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/103.0.0/Gaudi/bin/gaudirun.py readDigi.py
==19843==
```

**Comment by mirguest** [comment]
I try to load EcalBarrelCollection + EcalBarrelContributionCollection:

```
--------------------------------------------------------------------------------
Command:            python /cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/103.0.0/Gaudi/bin/gaudirun.py readDigi.py
Massif arguments:   --massif-out-file=valgrindmassif.output.log
ms_print arguments: valgrindmassif.output.log
--------------------------------------------------------------------------------


    MB
492.9^                                                                  #
     |                          @ :    :@  :::   : :::::  :  :@::::::@: #:::::
     |              ::::::::::::@:::::::@:::: ::@:::::::::::::@::::::@::#:::::
     |              ::::: ::::::@:::::::@: :: ::@:::::::::::::@::::::@::#:::::
     |              ::::: ::::::@:::::::@: :: ::@:::::::::::::@::::::@::#:::::
     |             @::::: ::::::@:::::::@: :: ::@:::::::::::::@::::::@::#:::::
     |             @::::: ::::::@:::::::@: :: ::@:::::::::::::@::::::@::#:::::
     |            @@::::: ::::::@:::::::@: :: ::@:::::::::::::@::::::@::#:::::
     |          @:@@::::: ::::::@:::::::@: :: ::@:::::::::::::@::::::@::#:::::
     |         :@:@@::::: ::::::@:::::::@: :: ::@:::::::::::::@::::::@::#:::::
     |      :@@:@:@@::::: ::::::@:::::::@: :: ::@:::::::::::::@::::::@::#:::::
     |      :@ :@:@@::::: ::::::@:::::::@: :: ::@:::::::::::::@::::::@::#:::::
     |      :@ :@:@@::::: ::::::@:::::::@: :: ::@:::::::::::::@::::::@::#:::::
     |     @:@ :@:@@::::: ::::::@:::::::@: :: ::@:::::::::::::@::::::@::#:::::
     |    @@:@ :@:@@::::: ::::::@:::::::@: :: ::@:::::::::::::@::::::@::#:::::
     |   @@@:@ :@:@@::::: ::::::@:::::::@: :: ::@:::::::::::::@::::::@::#:::::
     |   @@@:@ :@:@@::::: ::::::@:::::::@: :: ::@:::::::::::::@::::::@::#:::::
     |  :@@@:@ :@:@@::::: ::::::@:::::::@: :: ::@:::::::::::::@::::::@::#:::::
     |  :@@@:@ :@:@@::::: ::::::@:::::::@: :: ::@:::::::::::::@::::::@::#:::::
     |  :@@@:@ :@:@@::::: ::::::@:::::::@: :: ::@:::::::::::::@::::::@::#:::::
   0 +----------------------------------------------------------------------->Gi
     0                                                                   56.89

Number of snapshots: 81
 Detailed snapshots: [4, 5, 6, 8, 10, 12, 13, 26, 34, 41, 57, 67, 72 (peak)]
```

**Comment by mirguest** [comment]
After adding all the corresponding contributions:
```python
inp = PodioInput("InputReader")
inp.collections = ["EcalBarrelCollectionMerged", "EcalBarrelContributionCollection",
                   "EcalEndcapRingCollection", "EcalEndcapRingContributionCollection",
                   "EcalEndcapsCollection", "EcalEndcapsContributionCollection",
                   "HcalBarrelCollection", "HcalBarrelContributionCollection",
                   "HcalEndcapsCollection", "HcalEndcapsContributionCollection",
                   "MCParticle"]
```
no memory leakage now:
```
--------------------------------------------------------------------------------
Command:            python /cvmfs/cepcsw.ihep.ac.cn/prototype/releases/externals/103.0.0/Gaudi/bin/gaudirun.py readDigi_guofangyi.py
Massif arguments:   --massif-out-file=valgrindmassif.output.log
ms_print arguments: valgrindmassif.output.log
--------------------------------------------------------------------------------


    MB
709.0^                                                   :
     |       :@@@@:: :::::::::::#:::::@:::@:::@:::@:::::::@:::::@::::@:::::@::
     |      ::@ @ : ::::: :: :::#:::: @:::@:::@:::@:::::::@:::::@::::@:::::@::
     |      ::@ @ : ::::: :: :::#:::: @:::@:::@:::@:::::::@:::::@::::@:::::@::
     |     :::@ @ : ::::: :: :::#:::: @:::@:::@:::@:::::::@:::::@::::@:::::@::
     |  @:::::@ @ : ::::: :: :::#:::: @:::@:::@:::@:::::::@:::::@::::@:::::@::
     |  @:::::@ @ : ::::: :: :::#:::: @:::@:::@:::@:::::::@:::::@::::@:::::@::
     |  @:::::@ @ : ::::: :: :::#:::: @:::@:::@:::@:::::::@:::::@::::@:::::@::
     |  @:::::@ @ : ::::: :: :::#:::: @:::@:::@:::@:::::::@:::::@::::@:::::@::
     |  @:::::@ @ : ::::: :: :::#:::: @:::@:::@:::@:::::::@:::::@::::@:::::@::
     |  @:::::@ @ : ::::: :: :::#:::: @:::@:::@:::@:::::::@:::::@::::@:::::@::
     |  @:::::@ @ : ::::: :: :::#:::: @:::@:::@:::@:::::::@:::::@::::@:::::@::
     |  @:::::@ @ : ::::: :: :::#:::: @:::@:::@:::@:::::::@:::::@::::@:::::@::
     | :@:::::@ @ : ::::: :: :::#:::: @:::@:::@:::@:::::::@:::::@::::@:::::@::
     | :@:::::@ @ : ::::: :: :::#:::: @:::@:::@:::@:::::::@:::::@::::@:::::@::
     | :@:::::@ @ : ::::: :: :::#:::: @:::@:::@:::@:::::::@:::::@::::@:::::@::
     | :@:::::@ @ : ::::: :: :::#:::: @:::@:::@:::@:::::::@:::::@::::@:::::@::
     | :@:::::@ @ : ::::: :: :::#:::: @:::@:::@:::@:::::::@:::::@::::@:::::@::
     | :@:::::@ @ : ::::: :: :::#:::: @:::@:::@:::@:::::::@:::::@::::@:::::@::
     | :@:::::@ @ : ::::: :: :::#:::: @:::@:::@:::@:::::::@:::::@::::@:::::@::
   0 +----------------------------------------------------------------------->Gi
     0                                                                   295.0
```

**Comment by mirguest** [comment]
Hi @qwert2333 , please try again.
