### ISSUE TITLE
Untagged commits

### ISSUE THREAD

**Issue by jmcarcell** [cepc/CEPCSW#255]
Dear CEPC friends,
we are going to make a new Key4hep release soon and the following commits in CEPCSW do not belong to any tag:
```
5789738 Merge pull request #253 from jmcarcell/k4lcioreader
f55f25e Remove k4LCIOReader
725a26e Merge pull request #252 from mirguest/master
e9cb444 Control the environment setup in build-k4.sh
87c3b8b update externals to 103.0.2
7edab5f Merge pull request #251 from fucd/tracking-fix
293277b remove DEBUG for Clupatra
```
If you want them to be part of the next release CEPCSW should be tagged, if not then just tell me and close this issue.

**Comment by mirguest** [comment]
Dear @jmcarcell,

Please find the latest tag https://github.com/cepc/CEPCSW/releases/tag/v0.2.8

Tao

**Comment by jmcarcell** [comment]
Thanks
