### ISSUE TITLE
WIP: implemet CEPC_v4 into CEPCSW/DetCEPCv4

### ISSUE THREAD

**Issue by fucd** [cepc/CEPCSW#29]
- [x] compact files
- [x] geometry construct
    - [x] Beampipe
    - [x] VXD
    - [x] SIT
    - [x] FTD
    - [x] TPC
    - [x] SET
    - [x] Ecal
    - [x] Hcal
    - [x] Coil
    - [x] Yoke
- [x] Validation

**Comment by fucd** [comment]
pull request #50 update geometry macth with CEPC_v4 much better.

**Comment by wenxingfang** [comment]
Hi @fucd 

For HCAL, I found  for same cell id, the distance between sim hit can be very large in Y direction, for example:

found id=12384899038775158,dis=131.796,x1=2294.77,y1=-25.2323,z1=442.641,x2=2295.34,y2=106.561,z2=442.182
found id=12103424062457718,dis=57.3574,x1=2455.15,y1=-32.7983,z1=433.53,x2=2455.15,y2=24.3344,z2=428.459
found id=12384899039037302,dis=65.3072,x1=2401.84,y1=31.2288,z1=440.192,x2=2401.69,y2=-33.8834,z2=435.15

Do you have any idea?

Best,
Wenxing

**Comment by fucd** [comment]
Hi @wenxingfang 

Thank you for your careful check. PR#134 seems fix this bug. If any more discover, please continue to feed back.

Chengdong

**Comment by fucd** [comment]
We will close this issue, if any more relative issue or problem, please create a new issue to discuss.
