### ISSUE TITLE
Update quickstart to reflect the example in CEPCSW tutorial 2020

### ISSUE THREAD

**Issue by xshi** [cepc/CEPCSW#38]
Please update the quickstart.md according to the example : 
https://indico.ihep.ac.cn/event/12341/session/5/contribution/3/material/slides/0.pdf

- [ ] Require "Fork" with "user" 
- [ ] git clone https://github.com/user/CEPCSW.git 
- [ ] Add the remote commands: 
- git remote add cepc https://github.com/cepc/CEPCSW.git
- git remote update
- git merge cepc/master

**Comment by xshi** [comment]
@mirguest Please update, thanks!

**Comment by mirguest** [comment]
Hi Xin,

It's fixed in PR #39 .

Tao
