### ISSUE TITLE
Migration from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by mirguest** [cepc/CEPCSW#59]
Both @fucd and I found that the CI does not run sometimes due to some API changes between Github and Travis-CI. The travis-ci.org will be closed soon, so we should migrate the CI to travis-ci.com

**Comment by mirguest** [comment]
Hi @xshi ,
We need your authorization on the travis-ci.com. Thank you!
Tao

**Comment by xshi** [comment]
Done.

**Comment by mirguest** [comment]
> Done.

Thanks @xshi . 

Could you also help us install the Travis CI into GitHub Apps?
https://github.com/apps/travis-ci/installations/new

Tao

**Comment by xshi** [comment]
Installed.

**Comment by mirguest** [comment]
The CI is workiong on Travis-CI.com.
